version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_datahub
    environment:
      POSTGRES_DB: datahub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5466:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
